spring:
  application:
    name: weather-api

openweather:
  base-url: https://api.openweathermap.org
  api-key: 6628efc6f8542970fe510a6a533c6fb3
  units: metric
  lang: pt_br
  
server:
  port: 8081
